{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Server",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"server\"} |= ``"
    }
   ]
  },
  {
   "title": "Client",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"client\"} |= ``"
    }
   ]
  },
  {
   "title": "Database",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{app=\"database\"} |= ``"
    }
   ]
  }
 ]
}